import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from typing import Dict, Any, List

class ReportGenerator:
    @staticmethod
    def generate_pdf(
        filename: str, 
        project_name: str, 
        author_name: str,
        circuit_name: str,
        results: Dict[str, Any],
        summary: str = "",
        formulas: List[str] = None
    ) -> str:
        """
        Generates a professional engineering PDF report for circuit simulation.
        Returns the absolute filepath to the created PDF.
        """
        # Ensure directories exist
        os.makedirs(os.path.dirname(filename), exist_ok=True)
        
        doc = SimpleDocTemplate(filename, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
        story = []
        
        styles = getSampleStyleSheet()
        
        # Define Custom Styles for High Aesthetics
        title_style = ParagraphStyle(
            name="TitleStyle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=26,
            textColor=colors.HexColor("#0F172A"), # Slate 900
            alignment=0, # Left aligned
            spaceAfter=15
        )
        
        subtitle_style = ParagraphStyle(
            name="SubtitleStyle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=12,
            textColor=colors.HexColor("#3b82f6"), # Blue 500
            spaceAfter=15
        )
        
        heading_style = ParagraphStyle(
            name="HeadingStyle",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=16,
            textColor=colors.HexColor("#1e293b"), # Slate 800
            spaceBefore=15,
            spaceAfter=8,
            keepWithNext=True
        )
        
        body_style = ParagraphStyle(
            name="BodyStyle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            textColor=colors.HexColor("#475569"), # Slate 600
            spaceAfter=10
        )
        
        th_style = ParagraphStyle(
            name="TableHeaderStyle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=colors.white
        )
        
        td_style = ParagraphStyle(
            name="TableCellStyle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            textColor=colors.HexColor("#334155")
        )
        
        # --- DOCUMENT TITLE & HEADER ---
        story.append(Paragraph("ElectraSim AI - Simulation Report", title_style))
        story.append(Paragraph(f"<b>Project:</b> {project_name} | <b>Circuit:</b> {circuit_name}", subtitle_style))
        story.append(Paragraph(f"<b>Author:</b> {author_name} | <b>Date:</b> {colors.HexColor('#000000')}", body_style))
        story.append(Spacer(1, 15))
        
        # --- CIRCUIT SUMMARY ---
        story.append(Paragraph("1. Executive Summary", heading_style))
        summary_text = summary or "This document contains the automated numerical simulation outputs, KCL/KVL parameters, and machine performance characteristics generated by the ElectraSim AI engineering suite."
        story.append(Paragraph(summary_text, body_style))
        story.append(Spacer(1, 10))
        
        # --- SIMULATION RESULTS TABLES ---
        if results:
            story.append(Paragraph("2. Simulation Operating Point Results", heading_style))
            
            # Form Voltages Table
            if "voltages" in results:
                story.append(Paragraph("Node Voltages:", ParagraphStyle(name="SubSub", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=11, spaceAfter=5)))
                data = [[Paragraph("Node Index", th_style), Paragraph("Voltage Potential (V)", th_style)]]
                for node, volt in results["voltages"].items():
                    data.append([
                        Paragraph(f"Node {node}", td_style),
                        Paragraph(f"{volt:.4f} V", td_style)
                    ])
                
                t = Table(data, colWidths=[200, 250])
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#0f172a")),
                    ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
                    ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor("#f8fafc"), colors.white]),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                    ('TOPPADDING', (0,0), (-1,-1), 6),
                ]))
                story.append(t)
                story.append(Spacer(1, 10))
                
            # Form Currents Table
            if "currents" in results:
                story.append(Paragraph("Branch Currents & Power Consumption:", ParagraphStyle(name="SubSub2", parent=styles["Normal"], fontName="Helvetica-Bold", fontSize=11, spaceAfter=5)))
                data = [
                    [
                        Paragraph("Component ID", th_style), 
                        Paragraph("Current (A)", th_style),
                        Paragraph("Power (W)", th_style)
                    ]
                ]
                for comp_id, curr in results["currents"].items():
                    power_val = results.get("power", {}).get(comp_id, 0.0)
                    data.append([
                        Paragraph(comp_id, td_style),
                        Paragraph(f"{curr:.4f} A", td_style),
                        Paragraph(f"{power_val:.4f} W", td_style)
                    ])
                
                t = Table(data, colWidths=[150, 150, 150])
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1e293b")),
                    ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
                    ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor("#f8fafc"), colors.white]),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                    ('TOPPADDING', (0,0), (-1,-1), 6),
                ]))
                story.append(t)
                story.append(Spacer(1, 15))
                
        # --- FORMULAS USED ---
        if formulas:
            story.append(Paragraph("3. Analytical Engineering Formulas", heading_style))
            for f in formulas:
                story.append(Paragraph(f"• {f}", body_style))
            story.append(Spacer(1, 10))
            
        # --- FOOTER SIGNATURE ---
        story.append(Spacer(1, 30))
        story.append(Paragraph("Report verified and generated by <b>ElectraSim AI</b>.", ParagraphStyle(name="Foot", parent=styles["Normal"], fontName="Helvetica-Oblique", fontSize=8, textColor=colors.HexColor("#94a3b8"))))
        
        doc.build(story)
        return filename
